### ISSUE TITLE
planetkit panics

### ISSUE THREAD

**Issue by wullewutz** [jeffparsons/planetkit#3]
Planetkit panicked at my machine (commit 17df8a..):

```
uname -srvo  
Linux 4.8.14-1-MANJARO #1 SMP PREEMPT Sat Dec 10 23:58:26 UTC 2016 GNU/Linux
```

```
cargo run              
    Finished debug [unoptimized + debuginfo] target(s) in 0.2 secs
     Running `target/debug/main`
pk_version: 0.0.1
  Dec 24 19:13:20.876 INFO Creating main window
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn\'t find any pixel format that matches the criterias."', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:837
```

I may provide a stacktrace if necessary.

**Comment by bjorn3** [comment]
Please rerun with RUST_BACKTRACE=1

**Comment by wullewutz** [comment]
```
stack backtrace:
   1:     0x55a49f8fe8fa - std::sys::imp::backtrace::tracing::imp::write::h0d1aacfb8fc693ac
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55a49f901a9f - std::panicking::default_hook::{{closure}}::hff87359baf5754d0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x55a49f90169e - std::panicking::default_hook::h936f17ca3b2b98dc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x55a49f901f47 - std::panicking::rust_panic_with_hook::he9c830ab830c7944
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x55a49f901dd4 - std::panicking::begin_panic::hbd10b7f500042f98
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x55a49f901cf9 - std::panicking::begin_panic_fmt::h49583ddd44614a0d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x55a49f901c87 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x55a49f92c7ed - core::panicking::panic_fmt::h3b787d0ceafd7204
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55a49f5b93d4 - core::result::unwrap_failed::hb53ada5fe8b46ab4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:29
  10:     0x55a49f58e881 - <core::result::Result<T, E>>::unwrap::h1c8b4a22d1e34078
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:737
  11:     0x55a49f63e41b - planetkit::window::make_window::h9e22db7a9339d071
                        at /home/wullewutz/w/3rd/planetkit/src/window.rs:15
  12:     0x55a49f640fba - planetkit::simple::new::h9d57c53485ddc9a9
                        at /home/wullewutz/w/3rd/planetkit/src/simple.rs:18
  13:     0x55a49f546bf4 - main::main::h697dd8e6a288b981
                        at /home/wullewutz/w/3rd/planetkit/src/bin/main.rs:4
  14:     0x55a49f908e0a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  15:     0x55a49f902686 - std::rt::lang_start::ha749a62502c90792
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  16:     0x55a49f546d82 - main
  17:     0x7fe49c76c290 - __libc_start_main
  18:     0x55a49f51f719 - _start
  19:                0x0 - <unknown>
```

**Comment by jeffparsons** [comment]
That's probably because I'm hard-coding the OpenGL version here.

```rust
    let opengl = OpenGL::V3_2;
    // ...
    let mut window: PistonWindow = WindowSettings::new(
        "planetkit",
        [800, 600]
    )
        .opengl(opengl)
        .exit_on_esc(true)
        .build()
        .unwrap();
```

It's on my mental list, but if anyone else wants to pick this off, I imagine the steps to fixing this are roughly:

1. Auto-detect the OpenGL version. At least support falling back to `OpenGL::V2_1` somehow. I haven't looked into how to detect what's available.
2. Translate `shaders/copypasta_150.glslv` and `shaders/copypasta_150.glslf` into GLSL 1.2. (That's the GLSL version that's compatible with OpenGL 2.1; see https://en.wikipedia.org/wiki/OpenGL_Shading_Language#Versions).

**Comment by jeffparsons** [comment]
...or I can switch to using Glium, which appears to take care of this for me, instead of PistonWindow.

**Comment by jeffparsons** [comment]
Oh, ok, I totally misread that. Glutin _doesn't_ solve the problem for me. Bummer.

@wullewutz Would you mind posting the output of `glxinfo`?

Unless I'm mistaken, the shortest path to me fixing this will be to set up a VM with only OpenGL 2.1 support, and hack around on that. So I'd like to verify that this is actually the issue first. :grin:

**Comment by jeffparsons** [comment]
Thanks!

I was assuming a driver that didn't support OpenGL 3+, but it looks like roughly the opposite: a _super modern_ driver (with OpenGL 4.5 support).

I'll have a play and see if I can reproduce this by playing around with Mesa configurations. It looks to me like I might be able to force it to expose different specific compatibility levels, but I'm super new to debugging OpenGL issues, so this might take a few swings.

**Comment by jeffparsons** [comment]
@wullewutz I'm afraid I haven't made any progress on this. In the hopes of trying to make it someone else's problem... 😄 

Do either of these examples (from the Gfx and Piston projects respectively) run on your machine?

- https://github.com/gfx-rs/gfx/tree/master/examples/cube
- https://github.com/PistonDevelopers/piston-examples/blob/master/src/cube.rs

**Comment by wullewutz** [comment]
@jeffparsons I now managed to build an run planetkit on my tower PC with nvidia graphic. 
I'm still failing on my laptop, but i guess this is more an issue it's intel gpu and piston.
I suggest you close this issue for it is not a bug of planetkit.
Thank you verry much for your help!

**Comment by jeffparsons** [comment]
Okay, no worries. :smile: I'll draw some inspiration from this thread a bit later for some kind of "troubleshooting" document.
