### ISSUE TITLE
ArchLinux

### ISSUE THREAD

**Issue by LogoiLab** [jeffparsons/planetkit#7]
This seems to be similar to issue 3. Manjaro is Arch based. I'm using vanilla Arch. Below is a stack trace. I just installed the latest bleeding edge version of X.Org (in case you don't know Arch is always bleeding edge with everything). This makes it a good distro for edge case testing.

```
pk_version: 0.0.1
  Feb 27 09:13:04.630 INFO Creating main window
thread 'main' panicked at 'Failed to get root window: XError { description: "GLXBadFBConfig", error_code: 181, request_code: 156, minor_code: 34 }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
stack backtrace:
   1:     0x5580a9a190ac - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5580a9a1c18e - std::panicking::default_hook::{{closure}}::hcc803c8663cda123
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x5580a9a1bd94 - std::panicking::default_hook::hd5bda4e453dfb4be
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x5580a9a1c62b - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x5580a9a1c4c4 - std::panicking::begin_panic::hc4c5d184a1e3fb7c
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x5580a9a1c3e9 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x5580a9a1c377 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:477
   8:     0x5580a9a46f8d - core::panicking::panic_fmt::h1016b85b51d1931f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x5580a99cdc18 - core::result::unwrap_failed::h8ca805782c93f1bc
  10:     0x5580a99d7fb3 - winit::api::x11::window::Window::new::he8df02577c6ca97d
  11:     0x5580a99d9a8a - winit::window::<impl winit::WindowBuilder>::build::hcc6aea1f81154d5a
  12:     0x5580a998d5f4 - glutin::platform::platform::x11::Window::new::h66d806b0c722ddb9
  13:     0x5580a99926be - glutin::window::<impl glutin::WindowBuilder<'a>>::build::h64aaa44c6f441a13
  14:     0x5580a996eca3 - glutin_window::GlutinWindow::new::h2cf3425256314d66
  15:     0x5580a9970978 - <glutin_window::GlutinWindow as window::BuildFromWindowSettings>::build_from_window_settings::h2e83e6407a359fb5
  16:     0x5580a993cca5 - planetkit::window::make_window::h9a7eb91ef4a7a164
  17:     0x5580a9942079 - planetkit::simple::new::h77804dc5a762dfa4
  18:     0x5580a98e96e6 - demo::main::h00e78e1ecf38f050
  19:     0x5580a9a234ea - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  20:     0x5580a9a1cd96 - std::rt::lang_start::ha0568cc91d8c5b09
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  21:     0x7fe5c70f6290 - __libc_start_main
  22:     0x5580a98e0c79 - _start
  23:                0x0 - <unknown>
```

**Comment by baskervald** [comment]
GLXBadFBConfig usually means your OpenGL version is too low, in my experience. I'm running Arch as well and it runs fine for me.

Run
```
glxinfo | grep OpenGL
```
and find the line that says "OpenGL core profile version string:"

**Comment by jeffparsons** [comment]
Hi @LogoiLab, and thanks for the feedback!

To help narrow down the issue, do either of these examples (from the Gfx and Piston projects respectively) run on your machine, or do they panic with a similar error?

- https://github.com/gfx-rs/gfx/tree/master/examples/cube
- https://github.com/PistonDevelopers/piston-examples/blob/master/src/cube.rs
